### ISSUE TITLE
deviseのインストール

### ISSUE THREAD

**Issue by yokohama** [yokohama/test_salon-1#3]
[こちら](https://qiita.com/matcham/items/3609e72360491543b1b6)を参考に、

Staffと、Memberまでを作成する。
以下のコマンドを実行する前に、installコマンドや設定ファイルの追加などもあるので、上記URLを参考にお願いします。

```
bundle exec rails g devise Staff
bundle exec rails g devise Member

bundle exec rake db:migrate
```

ここまでできたら、`rails c`で、それぞれ作成されていることを確認。

**Comment by minty1202** [comment]
ありがとうございます
